# Set the base image using Python 3.12
FROM python:3.12

# Set the working directory to /app
WORKDIR /app

# Copy only the necessary files to the working directory
COPY requirements.txt /app

# Install the requirements
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

RUN rm -f /app/requirements.txt

# Expose the port the app runs on
EXPOSE 7777

# Run the app with the Litestar CLI:
#   - It is only for development, for this reason the options 'pdb' (enable debug 
#      with an exception) and 'reload' (when the source file is changed)
CMD ["litestar", "run", "--pdb", "--reload", "--host", "0.0.0.0", "--port", "7777"]
