
-- ------------------------------------
-- Create user and grant privileges
-- ------------------------------------

CREATE USER __db_user__ WITH ENCRYPTED PASSWORD __db_pass__;
GRANT ALL PRIVILEGES ON DATABASE __db_name__ to __db_user__;


-- ----------------------------
-- Create tables
-- ----------------------------

-- Test table
CREATE TABLE test (
        -- Internal ID
        id             bigint 			     GENERATED BY DEFAULT AS IDENTITY
                                                     CONSTRAINT test_id_pk
                                                     PRIMARY KEY,
        -- Test payload
        test_id        bigint                        CONSTRAINT test_test_id_nn
                                                     NOT NULL
);

CREATE INDEX test_test_id_idx ON test USING btree(test_id);


-- ----------------------------
-- Populate test data
-- ----------------------------

INSERT INTO test (test_id)
VALUES(77);


-- ----------------------------
-- Grant the needed permissions
-- ----------------------------

GRANT USAGE ON SCHEMA public TO __db_user__;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO __db_user__;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO __db_user__;
